export const customFlavorTextGer = {
  899: "Die schwarzen Kugeln leuchten auf ominöse Weise, wenn es unsichtbare Wände erschafft. Das Barthaar, das es verliert, wird als Material für warme Winterkleidung hoch geschätzt.",
  900: "Ein extrem seltenes Erz, das in Vulkanregionen zu finden ist, löste seine Entwicklung aus, bei der Teile seines Körpers zu Stein wurden.",
  901: "Vermutlich ist das sumpfige Gelände Hisuis der Grund für seine robuste Statur sowie die neu errungene Fähigkeit, Torf nach Belieben manipulieren zu können.",
  902: "Es hüllt seinen Körper in die Seelen von Artgenossen, die auf dem beschwerlichen Weg zum Fluss ihrer Geburt ihr Leben ließen.",
  903: "Im frostigen Hochland kann diesem Einzelgänger kein anderes Pokémon das Wasser reichen, da er neben hochwirksamem Gift über herausragende körperliche Fähigkeiten verfügt.",
  904: "Selbst im Schlaf reagieren Myriadors Giftstacheln von allein und spießen alles auf, was sich ihm nähert.",
  905: "Kommt es übers Meer geflogen, neigt sich der harsche Winter dem Ende zu. Der Volksmund sagt, dass dank seiner Liebe neues Leben in Hisui Knospen treibe.",
  906: "Die Zusammensetzung seines weichen Fells ähnelt der von Pflanzen. Es reinigt penibel sein Gesicht, um zu verhindern, dass dieses austrocknet.",
  907: "Es lenkt geschickt die Ranke, die es unter seinem langen Fell verbirgt, und schleudert die harte Knospe an ihrem Ende auf Gegner.",
  908: "Es erweckt den Eindruck, als würde seine Blume schweben, indem es ihren Stiel mit der Reflexion des Fells an der Innenseite seines Mantels tarnt.",
  909: "Es legt sich auf warme Steine und nimmt so über seine rechteckigen Schuppen Hitze auf, mit der es Feuer-Energie erzeugt.",
  910: "Seine Feuer-Energie und sein Überschuss an Lebenskraft brachten gemeinsam den eiförmigen Feuerball auf seinem Kopf hervor.",
  911: "Der feurige Vogel, der durch Skelokroks Gesang die Gestalt ändert, soll eine Seele sein, die sich in dem Feuerball auf seinem Kopf niederließ.",
  912: "Vor langer Zeit kam es von weit her und ließ sich in Paldea nieder. Über sein Gefieder sondert es ein Gel ab, das Wasser und Schmutz abweist.",
  913: "Es rennt eifrig durch seichte Gewässer, um seine Beine zu stärken, und konkurriert mit Artgenossen darum, wer die anmutigste Beinarbeit vorweist.",
  914: "Mit einem einzigen Tritt kann es Lastwagen umwerfen. Es nutzt seine kräftigen Beine, um Tänze aus fernen Ländern aufzuführen.",
  915: "Es verfügt über einen fantastischen Geruchssinn, nutzt diesen aber ausschließlich zur Futtersuche, der es sich den lieben langen Tag widmet.",
  916: "Seine glatte, glänzende Haut ist sein ganzer Stolz. Über die Spitze seines Schwanzes setzt es einen konzentrierten Duft frei.",
  917: "Die Fadenkugel, die seinen Körper umgibt, ist sehr elastisch. Selbst die Sicheln seines natürlichen Feindes Sichlor prallen an ihr ab.",
  918: "Spinsidias hängt sich mit seinem Faden an Äste oder Decken und bewegt sich lautlos. Es erlegt seine Beute, bevor diese es bemerken kann.",
  919: "Sein drittes Beinpaar ist eingeklappt. In einer Notlage kann es dank dessen Kraft mehr als 10 m weit springen.",
  920: "Macht es ernst, so stellt es sich auf sein zuvor eingeklapptes Beinpaar und schaltet in den Showdown-Modus. So bezwingt es Gegner im Nu.",
  921: "Seine elektrischen Backentaschen sind nicht ganz ausgebildet. Um Strom zu erzeugen, muss es mit den Ballen der Vorderpfoten kräftig daran reiben.",
  922: "Wird seine Kolonie angegriffen, stürzt es sich sofort in den Kampf und besiegt den Feind mit Kampftechniken, die auf Elektroschocks setzen.",
  923: "Dieses Pokémon ist für gewöhnlich sehr gelassen, doch sobald ein Kampf beginnt, streckt es den Gegner mit blitzschnellen Bewegungen zu Boden.",
  924: "Zwieps arbeiten perfekt im Team zusammen. Sie nagen mit den Vorderzähnen Material für den Nestbau ab und tragen es dann davon.",
  925: "Auf einmal waren sie zu viert. Die Gruppe wirkt wie eine Familie, doch ob das wirklich der Wahrheit entspricht, ist unklar.",
  926: "Dieses Pokémon fühlt sich glatt und feucht an. Sein Atem enthält Hefe und bringt so alles in der Umgebung zum Gären.",
  927: "Da der wohlige Duft, den sein Körper verströmt, das Wachstum von Weizen begünstigt, schätzt man dieses Pokémon in Bauerndörfern sehr.",
  928: "Um sich vor Feinden zu schützen, sondert es aus der Frucht auf seinem Kopf Öl ab. Dieses ist so bitter, dass es einen zusammenzucken lässt.",
  929: "Bereitwillig teilt dieses Pokémon sein köstliches, frisch duftendes Öl mit anderen. Seit langer Zeit schon lebt es Seite an Seite mit den Menschen.",
  930: "Dieses Pokémon ist sehr friedlich und gütig. Es teilt sein leckeres, nährstoffreiches Öl mit geschwächten Pokémon.",
  931: "Diese Pokémon leben bevorzugt in Städten. Sie bilden nach Gefiederfarbe sortierte Gruppen und tragen untereinander Revierkämpfe aus.",
  932: "Es entstand in unterirdischen Salzschichten. Da es kostbares Salz mit den Menschen teilt, wurde es früher ganz besonders geschätzt.",
  933: "Um seine Beute einzupökeln, überschüttet es sie mit Salz, das es auf sie spuckt. Dieser Prozess entzieht dem Körper der Beute Wasser.",
  934: "Es reibt seine Fingerspitzen aneinander, um Salz auf verwundete Pokémon zu streuen. Dieses heilt selbst schwere Verletzungen im Nu.",
  935: "Ein verbranntes Stück Holzkohle ist als Pokémon zum Leben erwacht. Es fordert selbst starke Gegner heraus und hat einen feurigen Kampfgeist.",
  936: "Es entwickelte sich durch die Rüstung eines heldenhaften Kriegers zu dieser Form. Crimanzo besitzt einen ausgeprägten Sinn für Loyalität.",
  937: "Die Flammenschwerter an beiden Armen lodern mit dem Groll eines Schwertkämpfers, der fiel, ehe er sein Ziel erreichen konnte.",
  938: "Es erzeugt Strom, indem es mit seinem Schwanz wedelt. Bei Gefahr warnt es seine Artgenossen, indem es seinen Kopf aufblinken lässt.",
  939: "Dehnt und kontrahiert es seinen elastischen Körper, erzeugt der Nabeldynamo in seinem Bauch große Mengen an Elektrizität.",
  940: "Trifft Wind auf seine Flügel, erzeugen deren Knochen Strom. Es fängt Beute, indem es ins Meer taucht und ihr einen Stromschlag verpasst.",
  941: "Dieses Pokémon verstärkt seine Elektrizität durch Aufblasen des Kehlsacks. Es nutzt den Wind, um innerhalb eines Tages 700 km weit zu fliegen.",
  942: "Es blickt stets finster drein, um von anderen ernst genommen zu werden, doch selbst weinende Kinder fangen bei seinem Anblick an zu lachen.",
  943: "Dieses Pokémon kann in seiner großen Wamme Energie speichern. Setzt es diese auf einen Schlag frei, werden dadurch Feinde hinfortgeblasen.",
  944: "Wer dieses friedfertige Pokémon verärgert, wird durch einen Biss mit seinen scharfen, giftgetränkten Schneidezähnen gelähmt.",
  945: "Es beschmiert seine Finger mit giftigem Speichel, der je nach Futter anders gefärbt ist, und malt damit Muster auf die Bäume im Wald.",
  946: "Weherba entstehen, wenn Seelen, die keinen Frieden finden, vom Wind fortgeweht werden und sich in verdorrtem Gras verheddern.",
  947: "Es öffnet die Zweige auf dem Kopf, um Beute zu verschlingen. Hat es dieser genug Lebensenergie entzogen, spuckt es sie aus und entsorgt sie so.",
  948: "Es lebt in feuchten Wäldern. Die Falten, die sich von seinem Körper lösen, sind gummiartig und sehr schmackhaft.",
  949: "Diese Pokémon gründen Kolonien, die tief im Wald leben. Sie können es nicht ausstehen, wenn ihnen Fremde zu nahe kommen.",
  950: "Dieses Pokémon lauert seiner Beute kopfüber an Klippen hängend auf. Da ihm dabei das Blut in den Kopf steigt, kann es nicht lange so ausharren.",
  951: "Je länger es Sonnenlicht tankt, desto intensiver werden die Scharfstoffe in seinem Körper und umso pikanter fallen seine Attacken aus.",
  952: "Sein roter Kopf wandelt Scharfstoffe in Feuer-Energie um und kann so feurig scharfe Flammen von sich geben.",
  953: "Es vermischt Erde und Sand mit Psycho-Kräften, um eine Schlammkugel zu formen. Diese schätzt es mehr als sein eigenes Leben.",
  954: "Der Körper, der die Kugel stützt, regt sich kaum. Daher nimmt man an, dass sich der wahre Körper des Pokémon im Inneren der Kugel befindet.",
  955: "Seine Fußspitzen schweben dank der Psycho-Kräfte, die von den Rüschen an seinem Bauch ausgehen, knapp 1 cm über dem Boden.",
  956: "Es macht Gegner bewegungsunfähig, indem es Psycho-Kräfte über seine großen Augen freisetzt. Entgegen seinem Äußeren ist es ziemlich brutal.",
  957: "Es schwingt seinen handgeschmiedeten Hammer, um sich zu schützen. Dieser wird ihm allerdings oft von Pokémon gestohlen, die Metall fressen.",
  958: "Es überfällt Gruppen von Gladiantri und Caesurio, um Metall zu sammeln, das es zum Herstellen seines großen, robusten Hammers benötigt.",
  959: "Es ist intelligent und verwegen. Mit seinem Hammer schlägt es Felsen in die Luft und zielt damit auf fliegende Krarmor.",
  960: "Es kann den Geruch eines Agiluza auf 20 m Entfernung wahrnehmen und versteckt sich daraufhin flugs im Sand.",
  961: "Entgegen seinem Äußeren ist es von grober Natur. Mit seinen langen Körpern nimmt es Beute in die Mangel und zieht sie in sein Nest.",
  962: "Zum Spaß füllt es seine Schürze aus Brustgefieder und ausgefallenen Federn mit allerlei Dingen, nur um diese von hoch oben wieder fallen zu lassen.",
  963: "Mit dem Wasserring an der Schwanzflosse spielt es gerne mit Artgenossen. Über Ultraschallwellen kann es die Gefühle anderer Lebewesen erfassen.",
  964: "Hört es die Hilferufe von Artgenossen, ändert es seine Form. Den Moment seiner Verwandlung zeigt es jedoch niemandem.",
  965: "Es soll entstanden sein, als ein unbekanntes Gift-Pokémon von einem Motor Besitz ergriff, der in einer Schrottfabrik zurückgelassen wurde.",
  966: "Mit seinen nunmehr acht Zylindern lässt es ein Gasgemisch aus Gift und Gesteinsmineralien explodieren, um daraus Energie zu gewinnen.",
  967: "Seit uralten Zeiten soll es Menschen auf seinem Rücken reiten lassen. Darstellungen davon finden sich auf 10 000 Jahre alten Wandmalereien.",
  968: "Wird es angegriffen, setzt es seine Borsten wie Fäuste ein, um damit einen Sturm aus Hieben zu entfesseln.",
  969: "Es absorbiert Nährstoffe von Höhlenwänden und bedeckt seinen Körper mit Blütenblättern, die aus kristallisiertem Gift bestehen.",
  970: "Erkennt es Gefahr, öffnet es seine kristallenen Blütenblätter, um aus seinem kegelförmigen Körper Strahlen abzufeuern.",
  971: "Es soll die Wiedergeburt eines streunenden Hunde-Pokémon sein, das starb, ohne je in Berührung mit Menschen gekommen zu sein.",
  972: "Man findet es meist schlafend auf Friedhöfen. Friedwuff ist das loyalste aller Hunde-Pokémon.",
  973: "Dieses Pokémon verknotet offenbar seinen Hals am Ansatz, damit die im Bauch gespeicherte Energie nicht über den Schnabel entweicht.",
  974: "Vor sehr langer Zeit verließ es das Meer, um an Land zu leben. Angeblich ist es eng mit Wailmer verwandt.",
  975: "Es wandert in eisigen Schneegebieten umher. Mit den starken Muskeln und der dicken Fettschicht unter seiner Haut schützt es seinen Körper.",
  976: "Wirft es überflüssige Teile seines Körpers ab, steigen seine Psycho-Kräfte. Der Geschmack des abgeworfenen Fleisches ist simpel, aber lecker.",
  977: "Es ist zwar ein Vielfraß, doch die Jagd liegt ihm nicht. Deshalb schließt es sich mit Nigiragi zusammen, um Beute zu fangen.",
  978: "Dieses kleine Drachen-Pokémon lebt im Maul von Heerashai, wodurch es vor Feinden geschützt ist.",
  979: "Als sein geballter Zorn einen kritischen Punkt überschritt, erlangte es Macht, die weit über die Grenzen seines physischen Körpers hinausgeht.",
  980: "Wird Suelord angegriffen, wehrt es sich, indem es dicke Stacheln ausfährt. Setzt es diese riskante Attacke ein, ist es bereit, aufs Ganze zu gehen.",
  981: "Aufgrund der synchronisierten Gehirnströme von Kopf und Schweif sind seine Psycho-Kräfte zehnmal so stark wie die von Girafarig.",
  982: "Mit seinem harten Schweif höhlt es tief unter der Erde Felsgestein aus, um seinen Bau zu graben. Dessen Gänge können bis zu 10 km lang werden.",
  983: "Allein das Caesurio an der Spitze seiner riesigen Armee kann sich zu Gladimperio entwickeln.",
  984: "In den letzten Jahren gab es Sichtungen dieses Pokémon. Eine Kreatur aus einem gewissen Buch stand Pate für den Namen Riesenzahn.",
  985: "Bisher wurde es nur ein Mal gesichtet. Es ähnelt einer rätselhaften Kreatur, die in einem alten Expeditionsbericht beschrieben wurde.",
  986: "Es ist gut möglich, dass es sich hierbei um jene Kreatur handelt, die in einem gewissen Buch unter dem Namen Wutpilz auftaucht.",
  987: "Einige seiner Merkmale erinnern an eine Kreatur namens Flatterhaar, die in einer gewissen Schrift erwähnt wurde.",
  988: "Dieses rätselhafte Pokémon weist Ähnlichkeit mit einer Kreatur auf, die in einem alten Buch als Kriechflügel vorgestellt wurde.",
  989: "Da es noch nie gefangen wurde, ist die Datenlage dürftig. Seine Merkmale decken sich mit einer in einem Expeditionsbericht beschriebenen Kreatur.",
  990: "Es ähnelt stark einer wissenschaftlichen Waffe, die einer esoterischen Zeitschrift zufolge von Außerirdischen auf den Planeten geschickt wurde.",
  991: "Seine Form ähnelt der eines Roboters, der laut einem Artikel in einer esoterischen Zeitschrift von einer antiken Zivilisation erschaffen wurde.",
  992: "Es ähnelt stark einem Cyborg, der laut einer Sonderausgabe einer esoterischen Zeitschrift die modifizierte Form eines gewissen Athleten ist.",
  993: "Es ähnelt einem Pokémon, das einer esoterischen Zeitschrift nach der Nachwuchs eines Trikephalo sein soll, welches sich in einen Roboter verliebte.",
  994: "Es ähnelt einem unbekannten Objekt, das einer esoterischen Zeitschrift nach ein zur Beobachtung der Menschheit entsandtes UFO sein soll.",
  995: "Es hat Ähnlichkeit mit einem Pokémon, das eine fragwürdige Zeitschrift als ein Despotar vorstellte, das eine Milliarde Jahre aus der Zukunft stammt.",
  996: "Mit seiner Rückenflosse absorbiert es Wärme und wandelt diese in Eis-Energie um. Je wärmer es ist, desto mehr Energie kann es speichern.",
  997: "Es friert die Luft ringsum ein, um sein Gesicht mit einer Maske aus Eis zu schützen und seine Rückenflosse in Eisklingen zu verwandeln.",
  998: "Aus seinem Maul stößt es unfassbare Kälte aus, die sogar glühendes Magma augenblicklich gefrieren lässt.",
  999: "Es entstand vor etwa 1500 Jahren in einer Schatztruhe. Wenn Diebe versuchen, den Schatz zu stehlen, saugt es ihnen die Lebensenergie aus.",
  1000: "Sein Körper soll aus 1000 Münzen bestehen. Es ist sehr umgänglich und schließt mit jedem rasch Freundschaft.",
  1001: "Der Groll einer Person, die dafür bestraft wurde, die Missetaten des Königs auf Tafeln festzuhalten, hüllte sich in Laub und wurde zu diesem Pokémon.",
  1002: "Baojian kann bis zu 100 t Schnee kontrollieren. In den Lawinen, die es auslöst, tollt es ganz arglos herum.",
  1003: "Die Angst, die in ein Gefäß für uralte Rituale gegossen wurde, hüllte sich in Steine und Erde und wurde zu diesem Pokémon.",
  1004: "Es kontrolliert Flammen von 3000 °C. Mühelos schwimmt es durch das Meer aus Lava, das es durch Schmelzen von Gestein und Kies erzeugt.",
  1005: "Möglicherweise handelt es sich hierbei um jene Kreatur, die in einem rätselhaften Expeditions-bericht als Donnersichel erwähnt wurde.",
  1006: "Es weist einige Ähnlichkeiten mit der Erfindung eines verrückten Wissenschaftlers auf, die in einer esoterischen Zeitschrift erwähnt wurde.",
  1007: "Offenbar ist dies die Kreatur Schwingenkönig, von der es in einem alten Expeditionsbericht hieß, sie habe die Erde mit bloßen Fäusten gespalten.",
  1008: "Es sind kaum Einzelheiten zu diesem Wesen bekannt, welches zwar Mopex ähnelt, aber weitaus stärker und grausamer ist.",
  1009: "Diese rätselhafte und wilde Kreatur ist nach einem Wassermonster benannt, das in einem alten Expeditionsbericht beschrieben wurde.",
  1010: "Viele seiner Merkmale entsprechen denen eines Viridium aus der Zukunft, welches in einer esoterischen Zeitschrift vorgestellt wurde.",
  1011: "Dieses Pokémon besteht aus zwei Individuen. Es hat sich mithilfe eines Apfels entwickelt, der nur in einer bestimmten Gegend angebaut wird.",
  1012: "Es soll entstanden sein, als ein Teemeister starb, bevor er sein Handwerk perfektioniert hatte, und sein Gram von einer Tasse Matcha Besitz ergriff.",
  1013: "Es gibt sich als Tee aus und versucht jenen, die es versehentlich trinken, die Lebensenergie auszusaugen. Allerdings wird es oft durchschaut.",
  1014: "Die Giftstoffe aus der Kette um seinen Hals haben all seine Muskeln stimuliert und ihm einen kräftigen Körper verliehen.",
  1015: "Die Potenzial entfaltenden Giftstoffe in der Kette haben sein Gehirn stimuliert und seine Psycho-Kräfte aufblühen lassen.",
  1016: "Die Kette an seinem Körper sondert Gift ab, durch dessen Stimulation es ein schönes Äußeres und eine bezaubernde Stimme erhalten hat.",
  1017: "Sein Typ ändert sich je nach aufgesetzter Maske. Es führt Gegner mit seinen flinken Bewegungen und Tritten an der Nase herum.",
  1018: "Es sammelt statische Elektrizität aus der Umgebung. Die Strahlen, die es auf allen Vieren abfeuert, sind extrem stark.",
  1019: "Sieben sogenannte „Schlangel“ leben in einem Apfel aus Nektar. Das Exemplar in der Mitte ist der Anführer.",
  1020: "Es gibt nur sehr wenige bestätigte Sichtungen, doch es existiert ein kurzes Video, auf dem es umherwütet und Flammensäulen ausspeit.",
  1021: "Man sagt, dass es mit den Blitzen, die es aus seinem Fell abfeuert, alles in seiner Umgebung zu Asche verbrennt. Genaueres ist nicht bekannt.",
  1022: "Es ähnelt einem Pokémon, das eine fragwürdige Zeitschrift als ein Terrakium vorstellte, das von einer bösartigen Organisation modifiziert wurde.",
  1023: "Es ähnelt einem rätselhaften Objekt, das einer esoterischen Zeitschrift nach eine ultramoderne Waffe sein soll, die wie Kobalium aussieht.",
  1024: "Es schützt sich, indem es Energie in harten Kristall umwandelt. Dieses Pokémon ist der Ursprung der Terakristallisierung.",
  1025: "Es gibt anderen giftige Mochi zu essen, die Kräfte und Begierden wecken, kettet sie so an sich und kontrolliert sie.",
};

export const customFlavorTextJa = {
  899: "黒い球体は、目に見えない壁を作るときに不気味な方法で光ります。失ったひげは、暖かい冬の服の材料として高く評価されています。",
  900: "火山地域に見られる非常に珍しい鉱石は、身体の一部が石になるという進化を引き起こしました。",
  901: "おそらく、ヒスイの湿地が彼の頑丈な体格の理由であり、トーフを自在に操る新たな能力を獲得しました。",
  902: "彼は、出生の川に向かう困難な道のりで命を落とした仲間の魂に体を包みます。",
  903: "凍える高地では、この孤独者に匹敵するポケモンはいません。彼は強力な毒と卓越した身体能力を持っています。",
  904: "眠っている間でも、ミリャドールの毒の棘は自動的に反応し、近づくものを刺します。",
  905: "海を越えて飛んでくると、厳しい冬は終わりに近づきます。民間伝承では、彼の愛によってヒスイに新しい命が芽生えると言われています。",
  906: "その柔らかい毛皮の組成は植物に似ています。顔が乾燥しないように、入念に顔を洗います。",
  907: "彼は長い毛の下に隠れているつるを巧みに操り、その先端にある硬いつぼみを敵に投げつけます。",
  908: "彼の花は、マントの内側の毛の反射を使って茎を隠すことで、浮いているように見えます。",
  909: "彼は温かい石の上に横になり、長方形のうろこで熱を吸収し、火のエネルギーを生成します。",
  910: "彼の火のエネルギーと余剰の生命力が一緒になって、頭の上に卵型の火の玉を生み出しました。",
  911: "スケロクロクの歌によって形を変える炎の鳥は、頭の上の火の玉に宿る魂だと言われています。",
  912: "昔、遠くから来てパルデアに定住しました。羽毛からは水と汚れを拒むゲルを分泌します。",
  913: "彼は浅い水を元気に駆け回り、脚力を鍛え、仲間と優雅な脚の動きの競争をします。",
  914: "一蹴りでトラックをひっくり返します。強い脚を使って、遠い国のダンスを披露します。",
  915: "素晴らしい嗅覚を持っていますが、食べ物を探すためだけに使い、ひたすらそのことに専念しています。",
  916: "滑らかで光沢のある肌は彼の誇りです。尾の先端から濃厚な香りを放出します。",
  917: "彼を囲む糸の球は非常に弾力があります。自然の敵であるシクローの鎌さえも弾き返します。",
  918: "スピンシディアは糸を使って枝や天井にぶら下がり、音もなく動きます。獲物が気づく前に仕留めます。",
  919: "彼の三番目の足のペアは折りたたまれています。危険なときには、その力を利用して10メートル以上跳ぶことができます。",
  920: "真剣になると、彼は折りたたまれていた足を使って立ち上がり、ショーダウンモードに切り替えます。これで敵をすぐに打ち負かします。",
  921: "彼の電気的な頬袋は完全に発達していません。電気を生成するためには、前足の肉球で強くこすらなければなりません。",
  922: "コロニーが攻撃されると、すぐに戦闘に突入し、電気ショックを使った戦闘技術で敵を打ち負かします。",
  923: "このポケモンは普段は非常に冷静ですが、戦いが始まると、瞬時に相手を地面に叩きつけます。",
  924: "ズイプスはチームワークが完璧です。彼らは前歯で巣作りのための材料をかじり、それを持ち去ります。",
  925: "突然、彼らは4匹になりました。グループは家族のように見えますが、それが本当かどうかは不明です。",
  926: "このポケモンは滑らかで湿った感触を持っています。彼の息には酵母が含まれており、周囲のものを発酵させます。",
  927: "彼が発する心地よい香りは小麦の成長を促進するため、農村では非常に重宝されています。",
  928: "敵から身を守るため、頭の上の果実から油を分泌します。この油は非常に苦く、思わず顔をしかめます。",
  929: "喜んでこのポケモンは、他の者と美味しく新鮮な香りのする油を分け合います。長い間、人間と共に生活しています。",
  930: "このポケモンは非常に平和的で親切です。弱ったポケモンに美味しく栄養価の高い油を分けます。",
  931: "これらのポケモンは主に都市に住んでいます。羽毛の色によってグループを形成し、互いに領土争いをします。",
  932: "地下の塩の層で生まれました。人々と貴重な塩を分け合うため、かつては特に重宝されていました。",
  933: "獲物を漬け込むために、彼は獲物に塩を吹きかけます。このプロセスは獲物の体から水分を奪います。",
  934: "彼は指先をこすり合わせて、負傷したポケモンに塩を振りかけます。これは重傷さえも瞬時に治癒します。",
  935: "燃えた木炭の一片がポケモンとして生き返りました。彼は強い敵にも挑戦し、燃えるような闘志を持っています。",
  936: "英雄的な戦士の鎧からこの形に進化しました。クリマンゾは忠誠心が強いです。",
  937: "両腕の炎の剣は、目標に達する前に倒れた剣士の怒りを燃え上がらせます。",
  938: "彼は尾を振って電気を生成します。危険が迫ると、彼は頭を点滅させて仲間に警告します。",
  939: "弾性のある体を伸ばしたり収縮させたりすることで、腹部のナベルダイナモが大量の電気を生成します。",
  940: "風が彼の翼に当たると、骨が電気を生み出します。彼は海に飛び込んで獲物を捕らえ、電撃を与えます。",
  941: "このポケモンは、喉袋を膨らませることで電気を強化します。風を利用して、1日で700 km飛びます。",
  942: "彼は他の者に真剣に受け止めてもらうために、常に厳しい表情をしていますが、泣いている子供でも彼を見ると笑い出します。",
  943: "このポケモンは大きなたるみにエネルギーを蓄えます。これを一度に解放すると、敵は吹き飛ばされます。",
  944: "この平和的なポケモンを怒らせると、鋭く毒が塗られた前歯で噛まれて麻痺します。",
  945: "彼は食べ物によって色が変わる毒の唾液を指に塗り、森の木に模様を描きます。",
  946: "ウェヘルバは、安らぎを見つけられない魂が風に吹き飛ばされ、枯れた草に絡まって生まれます。",
  947: "彼は頭の枝を開いて獲物を呑み込みます。十分な生命エネルギーを吸収すると、彼はそれを吐き出して処分します。",
  948: "彼は湿った森に住んでいます。彼の体から剥がれ落ちるひだはゴムのようで非常に美味しいです。",
  949: "これらのポケモンは森の奥深くに住むコロニーを形成します。彼らは見知らぬ人が近づくのを非常に嫌います。",
  950: "このポケモンは崖に逆さにぶら下がって獲物を待ち伏せします。これにより、血が頭に上るため、長時間は耐えられません。",
  951: "太陽の光を長く浴びるほど、体内の香辛料が強くなり、攻撃もより辛くなります。",
  952: "赤い頭は香辛料を火のエネルギーに変え、激しい炎を放つことができます。",
  953: "地面と砂をサイコパワーで混ぜ合わせ、泥の玉を形成します。これを自分の命よりも大切にしています。",
  954: "玉を支える体はほとんど動きません。そのため、ポケモンの真の体は玉の内部にあると考えられています。",
  955: "足の先端は、お腹のフリルから放出されるサイコパワーによって、地面からわずか1 cm浮いています。",
  956: "大きな目からサイコパワーを放出して、相手を動けなくします。見た目に反して、かなり残忍です。",
  957: "鍛造されたハンマーを振るって自分を守りますが、金属を食べるポケモンにしばしば奪われます。",
  958: "グラディアントやケイジュリオの群れを襲って、頑丈なハンマーを作るために必要な金属を集めます。",
  959: "彼は賢く大胆です。ハンマーで岩を空中に打ち上げ、飛んでいるカラモールを狙います。",
  960: "20メートル離れた場所にいるアギルザの匂いを感知し、その後すぐに砂に隠れます。",
  961: "外見に反して粗野な性格です。長い体を使って獲物を捕らえ、巣に引き入れます。",
  962: "楽しみのために、胸の羽毛と装飾的な羽でエプロンをいっぱいにし、高い場所から落とします。",
  963: "尾の水のリングで仲間と遊ぶのが好きです。超音波で他の生物の感情を感じ取ります。",
  964: "仲間の助けを求める声を聞くと、形を変えますが、その変身の瞬間は誰にも見せません。",
  965: "ある未知の毒ポケモンがスクラップ工場に放置されたエンジンに取り憑いたとされ、これが彼の起源です。",
  966: "現在の8つのシリンダーで、毒と岩石鉱物の混合ガスを爆発させてエネルギーを得ています。",
  967: "古代から、人々を背中に乗せていたとされ、1万年前の壁画にもその描写が残っています。",
  968: "攻撃されると、トゲを使って攻撃し、強力な攻撃を繰り出します。",
  969: "洞窟の壁から栄養素を吸収し、体を結晶化した毒の花びらで覆います。",
  970: "危険を感じると、結晶の花びらを開いて、円錐形の体からビームを発射します。",
  971: "人間と接触することなく死んだ迷い犬ポケモンの再生とされている。",
  972: "主に墓地で眠っているのを見つけることができます。フリードヴッフは最も忠実な犬ポケモンです。",
  973: "このポケモンは、おそらく体内に蓄えたエネルギーがくちばしから漏れないように、首を結びつけています。",
  974: "とても昔、海を離れ陸に住むようになりました。ワイルマーと非常に近い関係にあると言われています。",
  975: "氷の雪原をさまよっています。強い筋肉と皮膚の下の厚い脂肪層で体を守ります。",
  976: "体の余分な部分を捨てると、サイコパワーが上昇します。捨てられた肉の味はシンプルですが美味しいです。",
  977: "大食いですが、狩りは得意ではありません。そのため、ニギラギと協力して獲物を捕まえます。",
  978: "この小さなドラゴンポケモンは、ヘーラシャイの口の中で生活し、敵から保護されています。",
  979: "怒りがピークを超えると、肉体を超えた力を得ます。",
  980: "スエルロードが攻撃されると、厚いトゲを出して反撃します。このリスクの高い攻撃を使用すると、全力で行きます。",
  981: "頭と尾の同期した脳波により、サイコパワーはジラファリグの10倍の強さを持っています。",
  982: "硬い尾で地下深くの岩石を掘り、自分の巣を作ります。そのトンネルは最大で10 kmにもなります。",
  983: "巨大な軍隊の先頭にいるカエスリオだけがグラディンペリオに進化できます。",
  984: "近年、このポケモンの目撃情報がありました。ある本の生物がこの名前の元になっています。",
  985: "これまでに一度だけ目撃されています。古い探検報告書に記載された謎の生物に似ています。",
  986: "この生物は、ある本に登場する「怒りのキノコ」に関連している可能性があります。",
  987: "そのいくつかの特徴は、ある書物で言及されている「フラッターヘア」という生物に似ています。",
  988: "この謎のポケモンは、古い本に紹介された「クリーチフリング」に似ています。",
  989: "まだ捕まったことがないため、データは乏しい。特徴は、探検報告書に記載された生物と一致しています。",
  990: "あるオカルトの雑誌によると、科学兵器に強く似ており、宇宙人によってこの惑星に送られたとされます。",
  991: "その形は、古代文明によって作られたロボットに非常によく似ていますと、あるオカルト雑誌の記事に記されています。",
  992: "あるオカルト雑誌の特別号によれば、あるアスリートの改造された形とされるサイボーグに強く似ています。",
  993: "あるオカルト雑誌によると、トライケファロの子孫とされるポケモンに似ています。このポケモンはロボットに恋をしたと言われています。",
  994: "あるオカルト雑誌によれば、人類を観察するために派遣されたUFOに似ている未知の物体です。",
  995: "ある問題の雑誌に紹介されたポケモンに似ており、未来から1億年離れたデスポタールとされています。",
  996: "背びれで熱を吸収し、これを氷のエネルギーに変えます。温度が高いほど、より多くのエネルギーを蓄えます。",
  997: "周囲の空気を凍らせて顔を氷のマスクで守り、背びれを氷の刃に変えます。",
  998: "口から放出する信じられないほどの冷気は、溶岩を瞬時に凍らせることができます。",
  999: "約1500年前、宝箱の中に出現しました。泥棒が宝を盗もうとすると、その命を吸い取ります。",
  1000: "その体は1000枚のコインでできているとされています。とても社交的で、誰とでもすぐに友達になります。",
  1001: "王の罪を記録するために罰を受けた人の恨みが葉に包まれ、このポケモンになりました。",
  1002: "バオジアンは最大で100トンの雪を操ることができます。彼が引き起こす雪崩の中で、無邪気に遊びます。",
  1003: "古代の儀式のために注がれた恐怖が石と土に包まれ、このポケモンになりました。",
  1004: "3000°Cの炎を操ります。彼が溶岩の海を作るとき、何の苦もなくそれを泳ぎます。",
  1005: "おそらくこれは、謎の探検報告書に記載された雷の鎌の生物です。",
  1006: "狂った科学者の発明に似ているとされ、あるオカルト雑誌に言及されています。",
  1007: "これは、古い探検報告書に、素手で地面を裂いたとされる生物、シュウィンキングのようです。",
  1008: "この生物についてはほとんど詳細が知られておらず、モペックスに似ていますが、はるかに強く残酷です。",
  1009: "この謎めいた野生の生物は、古い探検報告書に記載された水の怪物にちなんで名付けられました。",
  1010: "彼の特徴の多くは、あるオカルト雑誌に紹介された未来のヴァリディウムに似ています。",
  1011: "このポケモンは二つの個体から成り立っています。特定の地域で栽培されるリンゴを使って進化しました。",
  1012: "茶の師匠が自分の技術を完成させる前に亡くなり、その悲しみがマッチャのカップを支配したとされています。",
  1013: "お茶を装って、誤って飲んだ人の命のエネルギーを吸い取ろうとしますが、よく見抜かれます。",
  1014: "首の鎖からの毒素が全ての筋肉を刺激し、力強い体を与えました。",
  1015: "鎖に含まれる潜在能力を引き出す毒素が脳を刺激し、サイコパワーを花開かせました。",
  1016: "体に付いている鎖は毒を放出し、それによって美しい外見と魅力的な声を得ました。",
  1017: "装着したマスクに応じてタイプが変わります。素早い動きとキックで敵を翻弄します。",
  1018: "周囲から静電気を集めます。四つん這いで発射するビームは非常に強力です。",
  1019: "七つの「蛇」が蜜のリンゴの中に住んでいます。中央の個体がリーダーです。",
  1020: "確認された目撃情報は非常に少ないですが、彼が暴れ回り炎の柱を吐き出している短いビデオがあります。",
  1021: "毛皮から放たれる雷で周囲のものをすべて灰にすると言われていますが、詳細は不明です。",
  1022: "あるオカルト雑誌によると、悪の組織によって改造されたテラキオンに似ています。",
  1023: "あるオカルト雑誌によれば、超近代的な武器であるという謎の物体に似ていると言われています。",
  1024: "エネルギーを硬い結晶に変えて自分を守ります。このポケモンはテラクリスタリゼーションの起源です。",
  1025: "他の有毒な餅を食べることで力や欲望を呼び起こし、それらを自分に縛り付けて制御します。",
};

export const customGeneraTextGer = {
  906: "Florakatzen-Pokémon",
  907: "Florakatzen-Pokémon",
  1011: "Apfelsirup-Pokémon",
  1012: "Matcha-Pokémon",
  1013: "Matcha-Pokémon",
  1014: "Lakaien-Pokémon",
  1015: "Lakaien-Pokémon",
  1016: "Lakaien-Pokémon",
  1017: "Masken-Pokémon",
  1018: "Legierungs-Pokémon",
  1019: "Apfelhydra-Pokémon",
  1020: "Paradox-Pokémon",
  1021: "Paradox-Pokémon",
  1022: "Paradox-Pokémon",
  1023: "Paradox-Pokémon",
  1024: "Terakristall-Pokémon ",
  1025: "Knechtungs-Pokémon",
};

export const customGeneraTextJa = {
  906: "草猫ポケモン",
  907: "草猫ポケモン",
  908: "マジシャンポケモン",
  909: "炎のワニポケモン",
  910: "炎のワニポケモン",
  911: "歌手ポケモン",
  912: "ひなポケモン",
  913: "練習ポケモン",
  914: "ダンスポケモン",
  915: "豚ポケモン",
  916: "豚ポケモン",
  917: "糸玉ポケモン",
  918: "罠ポケモン",
  919: "バッタポケモン",
  920: "バッタポケモン",
  921: "マウスポケモン",
  922: "マウスポケモン",
  923: "ハンズオンポケモン",
  924: "カップルポケモン",
  925: "家族ポケモン",
  926: "子犬ポケモン",
  927: "犬ポケモン",
  928: "オリーブポケモン",
  929: "オリーブポケモン",
  930: "オリーブポケモン",
  931: "オウムポケモン",
  932: "岩塩ポケモン",
  933: "岩塩ポケモン",
  934: "岩塩ポケモン",
  935: "炎の子供ポケモン",
  936: "炎の戦士ポケモン",
  937: "炎の刃ポケモン",
  938: "電タドポケモン",
  939: "電カエルポケモン",
  940: "嵐のウミツバメポケモン",
  941: "フリゲートバードポケモン",
  942: "いたずらポケモン",
  943: "ボスポケモン",
  944: "毒マウスポケモン",
  945: "毒サルポケモン",
  946: "タンブルウィードポケモン",
  947: "タンブルウィードポケモン",
  948: "ウッドイヤーポケモン",
  949: "ウッドイヤーポケモン",
  950: "待ち伏せポケモン",
  951: "スパイシーペッパーポケモン",
  952: "スパイシーペッパーポケモン",
  953: "ローリングポケモン",
  954: "ローリングポケモン",
  955: "フリルポケモン",
  956: "ダチョウポケモン",
  957: "金属職人ポケモン",
  958: "ハンマーポケモン",
  959: "ハンマーポケモン",
  960: "ガーデンイールポケモン",
  961: "ガーデンイールポケモン",
  962: "アイテムドロップポケモン",
  963: "イルカポケモン",
  964: "イルカポケモン",
  965: "シングルシリンダーポケモン",
  966: "マルチシリンダーポケモン",
  967: "マウントポケモン",
  968: "ミミズポケモン",
  969: "鉱石ポケモン",
  970: "鉱石ポケモン",
  971: "ゴースト犬ポケモン",
  972: "ゴースト犬ポケモン",
  973: "シンクロポケモン",
  974: "テラクジラポケモン",
  975: "テラクジラポケモン",
  976: "放出ポケモン",
  977: "大ナマズポケモン",
  978: "模倣ポケモン",
  979: "怒りのサルポケモン",
  980: "トゲ魚ポケモン",
  981: "長い首ポケモン",
  982: "陸のヘビポケモン",
  983: "大きな刃ポケモン",
  984: "パラドックスポケモン",
  985: "パラドックスポケモン",
  986: "パラドックスポケモン",
  987: "パラドックスポケモン",
  988: "パラドックスポケモン",
  989: "パラドックスポケモン",
  990: "パラドックスポケモン",
  991: "パラドックスポケモン",
  992: "パラドックスポケモン",
  993: "パラドックスポケモン",
  994: "パラドックスポケモン",
  995: "パラドックスポケモン",
  996: "氷のヒレポケモン",
  997: "氷のヒレポケモン",
  998: "氷のドラゴンポケモン",
  999: "コインチェストポケモン",
  1000: "コインエンティティポケモン",
  1001: "遺物ポケモン",
  1002: "遺物ポケモン",
  1003: "遺物ポケモン",
  1004: "遺物ポケモン",
  1005: "パラドックスポケモン",
  1006: "パラドックスポケモン",
  1007: "パラドックスポケモン",
  1008: "パラドックスポケモン",
  1009: "パラドックスポケモン",
  1010: "パラドックスポケモン",
  1011: "キャンディアップルポケモン",
  1012: "抹茶ポケモン",
  1013: "抹茶ポケモン",
  1014: "リテイナーポケモン",
  1015: "リテイナーポケモン",
  1016: "リテイナーポケモン",
  1017: "マスクポケモン",
};
